### ISSUE TITLE
Logo popup vs. warning dialogue 

### ISSUE THREAD

**Issue by janitress** [Fleex255/Abiathar-Support#3]
when I drag&drop an _.adeps_ dependency file onto a newer _abiathar.exe_ version (newer than the dependency file) two popups are conflicting. like seen in the image below the logo popup overlays a warning dialogue. At this point I need to check the warning dialogue in order to continue but can't cause the logo popup blocks it...

Screenshot: _Popup overlay vs. warning dialogue_
![Abiathar_Popup_vs_Warning](https://s19.postimg.cc/5quhxtvmr/Abiathar_Popup_vs_Warning.png)

Screenshot: _Warning dialogue without the popup_
![Abiathar Warning](https://s19.postimg.cc/wooezknzn/Abiathar_Popup_vs_Warning2.png)

**Comment by Fleex255** [comment]
Fixed in v2.11 Snapshot 3.
