### ISSUE TITLE
Logo Contribution

### ISSUE THREAD

**Issue by janitress** [Fleex255/Abiathar-Support#5]
I had this idea for a tile font logo:
![SAIO](https://s19.postimg.cc/ixrdug1wz/ABIATHAR_new_tile-font_logo2.png)

**Comment by Fleex255** [comment]
That looks pretty neat, thanks!

I plan on doing main logo changes only on major version bumps. For example, v2.0 changed the logo from [this astonishingly ugly thing](https://i.imgur.com/lVCqLwd.png) to the current one.

I'll keep this contribution in mind for v3.0!
