### ISSUE TITLE
Script-Request: Counting point items for each level

### ISSUE THREAD

**Issue by janitress** [Fleex255/Abiathar-Support#7]
**Request:**
> _Out of curiosity, what level in Secret of the Oracle has the most neural stunners?_ How can I measure the number of point items each level has?
(asked in the [forums](https://keenmodding.org/viewtopic.php?f=24&t=3060&p=22662#p22662))

**Comment by Fleex255** [comment]
Ah, thanks for reminding me about this. To find how many of something each level has, you can us PSThar!

```
Get-Level | % {
	$script:stunners = 0
	$_ | %t {
		$f = $_ | Get-LevelTile $x $y 1
		$i = $_ | Get-LevelTile $x $y 2
		If ($f -in (0x67B, 0x68D)) { $script:stunners++ } # Foreground tiles
		If ($i -in (0x44, 0x22)) { $script:stunners++ }   # Infoplane tiles
	}
	$obj = [psobject]::new()
	$obj | Add-Member NoteProperty 'Level' ($_.Name)
	$obj | Add-Member NoteProperty 'Stunners' $stunners
	$obj
} | sort Stunners -Desc
```

That script counts stunners. To count something else, change the tile ID lists on the two labeled lines. If you want to change the property name, make sure to adjust both the second `Add-Member` call and the `sort`.

To find how many of an item there is in *one specific* level, enable Tools | "Resource Accountant: count items by item type" in the Configuration dialog, then use the Resource Accountant.
